//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanbo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hanbo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3pointCircle {
            get {
                object obj = ResourceManager.GetObject("_3pointCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3pointCircle_blue {
            get {
                object obj = ResourceManager.GetObject("_3pointCircle_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap angle {
            get {
                object obj = ResourceManager.GetObject("angle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap angle_blue32 {
            get {
                object obj = ResourceManager.GetObject("angle_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動 (Auto).
        /// </summary>
        public static string Button_Auto {
            get {
                return ResourceManager.GetString("Button_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消自動 (Cancel).
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影像裝置尚未準備完成 ( Camera is not ready).
        /// </summary>
        public static string CameraNotReadyMessage {
            get {
                return ResourceManager.GetString("CameraNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clearList_32 {
            get {
                object obj = ResourceManager.GetObject("clearList_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ConnectionStatus {
            get {
                return ResourceManager.GetString("ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coordinateXY_24 {
            get {
                object obj = ResourceManager.GetObject("coordinateXY_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crossPoint {
            get {
                object obj = ResourceManager.GetObject("crossPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crossPoint_blue32 {
            get {
                object obj = ResourceManager.GetObject("crossPoint_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distance {
            get {
                object obj = ResourceManager.GetObject("distance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distance_blue32 {
            get {
                object obj = ResourceManager.GetObject("distance_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distanceX {
            get {
                object obj = ResourceManager.GetObject("distanceX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distanceX_32 {
            get {
                object obj = ResourceManager.GetObject("distanceX_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distanceY {
            get {
                object obj = ResourceManager.GetObject("distanceY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap distanceY_32 {
            get {
                object obj = ResourceManager.GetObject("distanceY_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳號/密碼不正確 or 帳號停用
        ///Account / Password uncorrect or Accout disabled..
        /// </summary>
        public static string DoLoginMessage {
            get {
                return ResourceManager.GetString("DoLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_circle {
            get {
                object obj = ResourceManager.GetObject("draw_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_circle_blue32 {
            get {
                object obj = ResourceManager.GetObject("draw_circle_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_line {
            get {
                object obj = ResourceManager.GetObject("draw_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_line_blue32 {
            get {
                object obj = ResourceManager.GetObject("draw_line_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_point {
            get {
                object obj = ResourceManager.GetObject("draw_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap draw_point_blue32 {
            get {
                object obj = ResourceManager.GetObject("draw_point_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯出 ( Export ).
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportFile {
            get {
                object obj = ResourceManager.GetObject("ExportFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        public static string FailCode {
            get {
                return ResourceManager.GetString("FailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗 ( Fail ).
        /// </summary>
        public static string FailMessage {
            get {
                return ResourceManager.GetString("FailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_image {
            get {
                object obj = ResourceManager.GetObject("folder_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap grident_22 {
            get {
                object obj = ResourceManager.GetObject("grident_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manigify.
        /// </summary>
        public static string ImageManigify {
            get {
                return ResourceManager.GetString("ImageManigify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string ImageMove {
            get {
                return ResourceManager.GetString("ImageMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ImageNone {
            get {
                return ResourceManager.GetString("ImageNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ImageZoom {
            get {
                return ResourceManager.GetString("ImageZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統裝置檢查若發生失敗，請依以下步驟進行故障排除
        ///If device checking result fail, follow the troubleshooting instructions to fix problem
        ///
        ///1。關閉程式 ( Close the program )
        ///2。重啟光源控制器/CCD 電源 ( Reset power of the light contorller /  CCD )
        ///3。重新啟動程式 ( Reopen the program ).
        /// </summary>
        public static string InitSystemDeviceForm_TroubleShootingMessage {
            get {
                return ResourceManager.GetString("InitSystemDeviceForm_TroubleShootingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lens {
            get {
                object obj = ResourceManager.GetObject("lens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 載入 ( Load ).
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此 3 點無法在目前選擇的區域中擬合最佳圓！( Can not fit the circle).
        /// </summary>
        public static string Message_3PointCircleWarning {
            get {
                return ResourceManager.GetString("Message_3PointCircleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法計算角度 (Angle calculate error).
        /// </summary>
        public static string Message_AngleError {
            get {
                return ResourceManager.GetString("Message_AngleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兩線段才可以計算角度 (Only two line can calculate the angle).
        /// </summary>
        public static string Message_AngleWarning {
            get {
                return ResourceManager.GetString("Message_AngleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap message_attention {
            get {
                object obj = ResourceManager.GetObject("message_attention", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未連接至影像裝置，是否連線？
        ///( Camera is not connection, do you want to connect ? ).
        /// </summary>
        public static string Message_CameraAutoConnectNotice {
            get {
                return ResourceManager.GetString("Message_CameraAutoConnectNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影像裝置資源被其他應用程式佔用，無法開啟
        ///( Camera is used by other program).
        /// </summary>
        public static string Message_CameraIsOccupied {
            get {
                return ResourceManager.GetString("Message_CameraIsOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera 使用中，請關閉其他使用 Camera 的視窗，再重新開啟！
        ///(Camera is used , please close the other camera window and reopen it).
        /// </summary>
        public static string Message_CameraUsed {
            get {
                return ResourceManager.GetString("Message_CameraUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認 (Confirm).
        /// </summary>
        public static string Message_Confirm {
            get {
                return ResourceManager.GetString("Message_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請先建立模型 (Create Model First, Please ).
        /// </summary>
        public static string Message_CreateModelFirstNotice {
            get {
                return ResourceManager.GetString("Message_CreateModelFirstNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兩線平行，無法計算交點！(Parallel line can not calculate the cross point).
        /// </summary>
        public static string Message_CrossPointWarning {
            get {
                return ResourceManager.GetString("Message_CrossPointWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將會刪除所有資料，是否刪除？
        ///(Are you sure to delete it ? ).
        /// </summary>
        public static string Message_DeleteNotice {
            get {
                return ResourceManager.GetString("Message_DeleteNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 將會刪除所選擇的資料，是否刪除？
        ///( Are you sure to delete the selected items ? ).
        /// </summary>
        public static string Message_DeleteSelectedItemNotice {
            get {
                return ResourceManager.GetString("Message_DeleteSelectedItemNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 點成圓幾何相依物件不存在 (Dependency objects does not exists).
        /// </summary>
        public static string Message_DependencyNotExists {
            get {
                return ResourceManager.GetString("Message_DependencyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告！
        ///有其他量測項目相依於此項目，確定刪除將會失去其他的量測結果
        ///Warning !
        ///Some other measurement are depend on this item, if remove it will lose the dependent measurement..
        /// </summary>
        public static string Message_DependencyWarning {
            get {
                return ResourceManager.GetString("Message_DependencyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算距離發生錯誤
        ///( Distance Calculation Error ).
        /// </summary>
        public static string Message_DistanceCalculationError {
            get {
                return ResourceManager.GetString("Message_DistanceCalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法計算 X 方向距離！(Can not calculate the x distance).
        /// </summary>
        public static string Message_DistanceXWarning {
            get {
                return ResourceManager.GetString("Message_DistanceXWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法計算 Y 方向距離！(Can not calculate the y distance).
        /// </summary>
        public static string Message_DistanceYWarning {
            get {
                return ResourceManager.GetString("Message_DistanceYWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒有任何量測輸出項目，確定要儲存此程式？
        ///( No exporting measurements. Are you sure to save this planning ? ).
        /// </summary>
        public static string Message_EmptyExportItemNotice {
            get {
                return ResourceManager.GetString("Message_EmptyExportItemNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到匹配的物件 ( No matching objects ).
        /// </summary>
        public static string Message_EmptyMatchingObjects {
            get {
                return ResourceManager.GetString("Message_EmptyMatchingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入程式描述 ( Input the planning description ).
        /// </summary>
        public static string Message_EmptyPlanningDescNotice {
            get {
                return ResourceManager.GetString("Message_EmptyPlanningDescNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入程式名稱 ( Input the planning name ).
        /// </summary>
        public static string Message_EmptyPlanningNameNotice {
            get {
                return ResourceManager.GetString("Message_EmptyPlanningNameNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必要檔案遺失，無法匯出 ( Some data lost, export error ).
        /// </summary>
        public static string Message_ExportError {
            get {
                return ResourceManager.GetString("Message_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯出檔案成功 ( Export success ).
        /// </summary>
        public static string Message_ExportSuccess {
            get {
                return ResourceManager.GetString("Message_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影像仍在擷取中. 確定停止?
        ///( Stop the image acquition ? ).
        /// </summary>
        public static string Message_ImageAcquitionStopNotice {
            get {
                return ResourceManager.GetString("Message_ImageAcquitionStopNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 影像格式錯誤，請選擇正確的影像檔案
        ///( Image format erro, please choice the right file).
        /// </summary>
        public static string Message_ImageFormatErrorNotice {
            get {
                return ResourceManager.GetString("Message_ImageFormatErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯入失敗 ( Import Fail ).
        /// </summary>
        public static string Message_ImportFail {
            get {
                return ResourceManager.GetString("Message_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案格式錯誤，無法匯入 ( File format error ).
        /// </summary>
        public static string Message_ImportFormatError {
            get {
                return ResourceManager.GetString("Message_ImportFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯入成功 ( Import Success ).
        /// </summary>
        public static string Message_ImportSuccess {
            get {
                return ResourceManager.GetString("Message_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入程式名稱及描述 ( Please input plan name and description ).
        /// </summary>
        public static string Message_InputPlanNameAndDescriptionNotice {
            get {
                return ResourceManager.GetString("Message_InputPlanNameAndDescriptionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光源控制器尚未連線，請確認電源及連接網路介面是否正確！
        ///( Light Controller disconnected, check the power and network interface to fix the problem ).
        /// </summary>
        public static string Message_LightControllerDisconnectedNotice {
            get {
                return ResourceManager.GetString("Message_LightControllerDisconnectedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 載入程序發生錯誤！請查看事件記錄器
        ///( Module loading fail, check the event log to fix problem).
        /// </summary>
        public static string Message_LoadingFail {
            get {
                return ResourceManager.GetString("Message_LoadingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到匹配模型 ( Can&apos;t find the matching model ).
        /// </summary>
        public static string Message_MatchingModelNotFound {
            get {
                return ResourceManager.GetString("Message_MatchingModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測量時發生錯誤 ( Measurement Error ! ).
        /// </summary>
        public static string Message_MeasurementError {
            get {
                return ResourceManager.GetString("Message_MeasurementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型建立完成,
        ///請按下一步繼續
        ///( Model created, press next step button to continue).
        /// </summary>
        public static string Message_ModelCreated {
            get {
                return ResourceManager.GetString("Message_ModelCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無資料
        ///(No data).
        /// </summary>
        public static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無影像 ( No image).
        /// </summary>
        public static string Message_NoImage {
            get {
                return ResourceManager.GetString("Message_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示 (Notice).
        /// </summary>
        public static string Message_Notice {
            get {
                return ResourceManager.GetString("Message_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式不存在，是否匯入？
        ///( Plan does not exist, import ? ).
        /// </summary>
        public static string Message_PlanDoesNotExistsNotice {
            get {
                return ResourceManager.GetString("Message_PlanDoesNotExistsNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式已存在，是否覆蓋？
        ///( Plan exists , overwrite ? ).
        /// </summary>
        public static string Message_PlanExistsNotice {
            get {
                return ResourceManager.GetString("Message_PlanExistsNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已開啟程式編輯，是否要關閉目前程式並載入？
        ///( Plan is opend, do you want to close the current plan, and reload the new one ? ).
        /// </summary>
        public static string Message_PlanOpendAndReloadNotice {
            get {
                return ResourceManager.GetString("Message_PlanOpendAndReloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已另存程式，是否開啟該程式？
        ///(  Planning saved. Re-open it ? ).
        /// </summary>
        public static string Message_PlanSaveAsSuccessedReloadItNotice {
            get {
                return ResourceManager.GetString("Message_PlanSaveAsSuccessedReloadItNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式儲存成功 ( Planning Saved).
        /// </summary>
        public static string Message_PlanSaved {
            get {
                return ResourceManager.GetString("Message_PlanSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法計算兩線之對稱線 (Symmetry line calculate error).
        /// </summary>
        public static string Message_SymmetryLineError {
            get {
                return ResourceManager.GetString("Message_SymmetryLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兩線段才可以計算對稱中線 (Only two line can calculate the symmetry line).
        /// </summary>
        public static string Message_SymmetryLineWarning {
            get {
                return ResourceManager.GetString("Message_SymmetryLineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訓練影像為空，請重新載入訓練影像
        ///( Training image is empty, reload it ).
        /// </summary>
        public static string Message_TrainingImageEmptyReloadNotice {
            get {
                return ResourceManager.GetString("Message_TrainingImageEmptyReloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未建立模型，請回到 Step1 建立模型
        ///( Model uncreated, return to step 1 to carate model ).
        /// </summary>
        public static string Message_UnCreateModelNotice {
            get {
                return ResourceManager.GetString("Message_UnCreateModelNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告 (Warnning).
        /// </summary>
        public static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3點成圓.
        /// </summary>
        public static string Model_3PointCircle {
            get {
                return ResourceManager.GetString("Model_3PointCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角度.
        /// </summary>
        public static string Model_Angle {
            get {
                return ResourceManager.GetString("Model_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統訊息 ( Message ).
        /// </summary>
        public static string Model_CheckMessage {
            get {
                return ResourceManager.GetString("Model_CheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢查結果 ( Result ).
        /// </summary>
        public static string Model_CheckResult {
            get {
                return ResourceManager.GetString("Model_CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交點.
        /// </summary>
        public static string Model_CrossPoint {
            get {
                return ResourceManager.GetString("Model_CrossPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述 ( Description ).
        /// </summary>
        public static string Model_Description {
            get {
                return ResourceManager.GetString("Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裝置名稱 ( Device).
        /// </summary>
        public static string Model_DeviceName {
            get {
                return ResourceManager.GetString("Model_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離.
        /// </summary>
        public static string Model_Distance {
            get {
                return ResourceManager.GetString("Model_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公差下限 (Lower limit).
        /// </summary>
        public static string Model_LowerLimit {
            get {
                return ResourceManager.GetString("Model_LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準值 (Normal value).
        /// </summary>
        public static string Model_Normal {
            get {
                return ResourceManager.GetString("Model_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對稱中線.
        /// </summary>
        public static string Model_SymmetryLine {
            get {
                return ResourceManager.GetString("Model_SymmetryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公差上限 (Upper limit).
        /// </summary>
        public static string Model_UppderLimit {
            get {
                return ResourceManager.GetString("Model_UppderLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 長度  (Length).
        /// </summary>
        public static string Model_WorldDistance {
            get {
                return ResourceManager.GetString("Model_WorldDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X 方向距離.
        /// </summary>
        public static string Model_XwayDistance {
            get {
                return ResourceManager.GetString("Model_XwayDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y 方向距離.
        /// </summary>
        public static string Model_YwayDistance {
            get {
                return ResourceManager.GetString("Model_YwayDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string OperationMode {
            get {
                return ResourceManager.GetString("OperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveDraw {
            get {
                object obj = ResourceManager.GetObject("saveDraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SuccessCode {
            get {
                return ResourceManager.GetString("SuccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功 ( Success ).
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap symmetryLine {
            get {
                object obj = ResourceManager.GetObject("symmetryLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap symmetryLine_blue32 {
            get {
                object obj = ResourceManager.GetObject("symmetryLine_blue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耗時 ( Time consumed ).
        /// </summary>
        public static string TimeConsumed {
            get {
                return ResourceManager.GetString("TimeConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap workspace_32 {
            get {
                object obj = ResourceManager.GetObject("workspace_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zoom_fit_best3 {
            get {
                object obj = ResourceManager.GetObject("zoom_fit_best3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap zoomLayer_24 {
            get {
                object obj = ResourceManager.GetObject("zoomLayer_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomRatio {
            get {
                return ResourceManager.GetString("ZoomRatio", resourceCulture);
            }
        }
    }
}
